Title Article Component complete
nology-tech/oae-event-programme pull request #13
Opened 2021-12-14 16:04 UTC by jasenscode

Component written
Styling added
Test written for component render and props working correctly, and confirmed as passing

2021-12-15 16:57 UTC, DanForder requested changes

2021-12-15 16:57 UTC, DanForder commented on src/assets/components/TitleArticle/TitleArticle.scss
> +    // font-family: $fontOne;
remove commented code/ unused scss rules

2021-12-15 16:57 UTC, DanForder commented on src/assets/components/TitleArticle/TitleArticle.scss
> +  font-family: "PT Sans";
create variable

2021-12-15 16:57 UTC, DanForder commented on src/assets/components/TitleArticle/TitleArticle.test.js
> +  const { container } = render(<TitleArticle />);
use customRender function

2021-12-15 16:58 UTC, DanForder commented
You have conflicts with app.jsx, make sure you pull from main and handle any conflicts

2021-12-16 17:39 UTC, DanForder requested changes

2021-12-16 17:39 UTC, DanForder commented on src/components/ViewScheduleButton/ViewScheduleButton.css
> +@import"https://fonts.googleapis.com/css2?family=PT+Sans&family=Poppins:wght@400;500;600;700&display=swap";@import"https://fonts.googleapis.com/css2?family=Lato&family=Playfair+Display:wght@400;500;6
remove this file

2022-01-04 14:36 UTC, jasenscode commented on src/components/ViewScheduleButton/ViewScheduleButton.css
> +@import"https://fonts.googleapis.com/css2?family=PT+Sans&family=Poppins:wght@400;500;600;700&display=swap";@import"https://fonts.googleapis.com/css2?family=Lato&family=Playfair+Display:wght@400;500;6
Removed

2022-01-04 14:54 UTC, DanForder approved these changes

2022-01-04 14:55 UTC, merged