Made component for date time and place section on the home page
nology-tech/oae-event-programme pull request #17
Opened 2021-12-15 15:18 UTC by Ankita-Manmoandas

-Component created
- styling added
- testing complete

2021-12-15 16:37 UTC, DanForder requested changes

2021-12-15 16:37 UTC, DanForder commented on src/assets/components/EventHeaderDetails/EventHeaderDetails.jsx
> +    <div className="event-details">
classname should match component name: 'event-header-details'

2021-12-15 16:37 UTC, DanForder commented on src/assets/components/EventHeaderDetails/EventHeaderDetails.scss
> +  background-color: #fa825d;
add as variables in _variables.scss

2021-12-15 16:37 UTC, DanForder commented on src/assets/components/EventHeaderDetails/EventHeaderDetails.test.js
> +import { render } from "@testing-library/react";
use new 'customRender' function found in utils/ testUtils file instead of 'render'

2021-12-15 16:37 UTC, DanForder commented on src/assets/components/EventHeaderDetails/EventHeaderDetails.jsx
> +      </p>
Does this component still look good if only a location is passed in as a prop? Make sure this component looks as expected with all combinations of props

2021-12-16 15:23 UTC, jasenscode commented on src/assets/components/EventHeaderDetails/EventHeaderDetails.jsx
> +    <div className="event-details">
className updated

2021-12-16 15:23 UTC, jasenscode commented on src/assets/components/EventHeaderDetails/EventHeaderDetails.scss
> +  background-color: #fa825d;
Pulled variable names from main and updated accordingly

2021-12-16 15:23 UTC, jasenscode commented on src/assets/components/EventHeaderDetails/EventHeaderDetails.test.js
> +import { render } from "@testing-library/react";
Updated to customRender

2021-12-16 15:24 UTC, jasenscode commented on src/assets/components/EventHeaderDetails/EventHeaderDetails.jsx
> +      </p>
Added conditional rendering to divider and comma spans and added tests

2021-12-16 17:02 UTC, DanForder approved these changes

2021-12-16 17:03 UTC, merged