Page title and sub home
nology-tech/oae-event-programme pull request #25
Opened 2022-01-04 15:49 UTC by Ankita-Manmoandas

added component, styling, and tests

2022-01-04 16:06 UTC, Ankita-Manmoandas commented
component, sass, and tests complete

2022-01-04 17:04 UTC, DanForder requested changes

2022-01-04 17:04 UTC, DanForder commented on .eslintrc.json
> +
undo this change

2022-01-04 17:04 UTC, DanForder commented on src/App.jsx
> +    <div>
Remove this wrapping div, it's not being used

2022-01-04 17:04 UTC, DanForder commented on src/assets/sass/_typography.css
> +@import"https://fonts.googleapis.com/css2?family=PT+Sans&family=Poppins:wght@400;500;600;700&display=swap";@import"https://fonts.googleapis.com/css2?family=Lato&family=Playfair+Display:wght@400;500;6
Remove this css file

2022-01-04 17:04 UTC, DanForder commented on src/assets/sass/_typography.scss
> +$modern-header-sub:'Oswald', sans-serif;
this font is the same irrespective of modern/ classic theme, so can just be something like $sub-heading-font

2022-01-04 17:05 UTC, DanForder commented
Please run prettier with NPM run prettier

2022-01-04 17:05 UTC, DanForder commented
Remove CSS files, we're using SCSS in the project

2022-01-04 17:08 UTC, DanForder requested changes

2022-01-05 08:54 UTC, DanForder requested changes

2022-01-05 08:54 UTC, DanForder commented on src/components/EventHeaderTitle/EventHeaderTitle.jsx
> +      <span className="header-home__title">{title}</span>
This one should still be an H1, just the subtitle needs to be span. We just want to make sure there's always exactly one H1 on each page

2022-01-05 12:48 UTC, DanForder requested changes

2022-01-05 12:48 UTC, DanForder commented on src/components/ViewScheduleButton/ViewScheduleButton.css
> +@import"https://fonts.googleapis.com/css2?family=PT+Sans&family=Poppins:wght@400;500;600;700&display=swap";@import"https://fonts.googleapis.com/css2?family=Lato&family=Playfair+Display:wght@400;500;6
remove css file

2022-01-05 14:55 UTC, merged