Feature youtube embed
nology-tech/oae-event-programme pull request #26
Opened 2022-01-04 16:30 UTC by jasenscode

Completed component

2022-01-04 17:15 UTC, DanForder requested changes

2022-01-04 17:15 UTC, DanForder commented on src/pages/Home/Home.jsx
> +      <EventHeaderDetails time="11.30am" date="Sun 21 Nov 2021" venue="South Bank" location="London" />
Remove repeated EventEHeaderDetails line

2022-01-04 21:35 UTC, jasenscode commented on src/pages/Home/Home.jsx
> +      <EventHeaderDetails time="11.30am" date="Sun 21 Nov 2021" venue="South Bank" location="London" />
Removed

2022-01-05 08:28 UTC, DanForder approved these changes

2022-01-05 08:51 UTC, merged