initialRequest
nology-tech/oae-event-programme pull request #27
Opened 2022-01-05 15:24 UTC by noahSerafin

snapshot testing done

2022-01-05 16:46 UTC, DanForder requested changes

2022-01-05 16:46 UTC, DanForder commented on src/components/HeaderImageVideoContainer/HeaderImageVideoContainer.jsx
> +  return <div className="header-container">{isVideo ? <YoutubeEmbed embedId={content} /> : <img src={content} className="header-image" alt="Event image" />}</div>;
classname should match name of component

2022-01-05 16:46 UTC, DanForder commented on src/components/HeaderImageVideoContainer/HeaderImageVideoContainer.test.js
> +});
add extra snapshot for isVideo true

2022-01-05 16:53 UTC, jasenscode commented on src/components/HeaderImageVideoContainer/HeaderImageVideoContainer.test.js
> +});
added

2022-01-05 16:53 UTC, jasenscode commented on src/components/HeaderImageVideoContainer/HeaderImageVideoContainer.jsx
> +  return <div className="header-container">{isVideo ? <YoutubeEmbed embedId={content} /> : <img src={content} className="header-image" alt="Event image" />}</div>;
amended

2022-01-05 16:59 UTC, DanForder approved these changes

2022-01-05 17:37 UTC, DanForder requested changes
fix merge conflicts

2022-01-06 08:44 UTC, DanForder approved these changes

2022-01-06 10:31 UTC, merged