Page header
nology-tech/oae-event-programme pull request #32
Opened 2022-01-06 16:06 UTC by noahSerafin

snapshots tests done

2022-01-07 13:03 UTC, DanForder requested changes

2022-01-07 13:03 UTC, DanForder commented on src/components/PageHeader/PageHeader.jsx
> +      : "page-header";
add a modifier class for --only:

```
let headerClass = 'page-header';
if(time, date, venue, location, content, isVideo) == null{
    headerClass += ' page-header--only';
}
```

2022-01-07 13:03 UTC, DanForder commented on src/pages/About/About.jsx
> +      <Photo imageSrc={OrchestraImg} alt="" description="-" />
description should be "earliest known photo of the orchestra", crop that mock image if needs be

2022-01-07 13:03 UTC, DanForder commented on src/pages/About/About.jsx
> +        content="aString"
use a real video here, doesn't need to be the right one, just make sure it's vaguely professional/ presentable to the client.

2022-01-07 13:03 UTC, DanForder commented on src/pages/Schedule/Schedule.jsx
> +      />
this should be dynamic based on the mock data file, look at how the home page is importing the event and follow that same code

2022-01-07 13:57 UTC, DanForder requested changes

2022-01-07 13:57 UTC, DanForder commented on src/components/PageHeader/PageHeader.jsx
> +      headerClass +=  "--only";
I mean to add an _extra_ modifier class, so it should be ` headerClass += " page-header--only"

2022-01-07 13:57 UTC, DanForder commented on src/components/PageHeader/PageHeader.scss
> +}
this can become just 
```
&--only{
    padding-bottom: 2rem;
}
```

2022-01-07 14:02 UTC, noahSerafin commented on src/components/PageHeader/PageHeader.scss
> +}
this didn't work for me earlier, maybe have a go with it yourself?

2022-01-07 14:03 UTC, noahSerafin commented on src/components/PageHeader/PageHeader.scss
> +}
oh wait i think i know what you mean now

2022-01-07 16:47 UTC, DanForder requested changes

2022-01-07 16:47 UTC, DanForder commented on src/components/PageHeader/PageHeader.jsx
> +      headerClass +=  "page-header--only";
need a space here: `" page-header--only"`

2022-01-10 08:41 UTC, jasenscode commented on src/components/PageHeader/PageHeader.jsx
> +      headerClass +=  "page-header--only";
Added

2022-01-10 08:48 UTC, DanForder approved these changes

2022-01-10 09:08 UTC, merged