Fix image event
nology-tech/oae-event-programme pull request #47
Opened 2022-01-12 15:52 UTC by noahSerafin

image now changes with different eventIds

2022-01-12 15:56 UTC, DanForder requested changes

2022-01-12 15:56 UTC, DanForder commented on src/pages/Home/Home.jsx
> +//import placeHolderImg from "../../assets/images/image33.png";
remove commented code

2022-01-12 15:56 UTC, DanForder commented on src/pages/Home/Home.jsx
> +  const { name, series, time, date, venue, location, content, theme, imageSrc } = event;
we need the image alt as well, not just image src

2022-01-12 15:58 UTC, noahSerafin commented on src/pages/Home/Home.jsx
> +//import placeHolderImg from "../../assets/images/image33.png";
removed

2022-01-12 17:04 UTC, DanForder requested changes

2022-01-12 17:04 UTC, DanForder commented on src/pages/Home/Home.jsx
> +          altcontent={imageAlt}
typoe : should be altContent

2022-01-13 14:52 UTC, DanForder approved these changes

2022-01-13 15:01 UTC, merged