added image and callout paragraph styling.
nology-tech/oae-event-programme pull request #54
Opened 2022-01-13 16:02 UTC by SamTo83

2022-01-13 16:29 UTC, DanForder requested changes

2022-01-13 16:29 UTC, DanForder commented on src/components/Layout/Layout.scss
> +  overflow-y: hidden;
you've overwritten this file, change it back !

2022-01-13 16:29 UTC, DanForder commented on src/components/PageHeader/PageHeader.jsx
> -            altContent={altContent}
you've overwritten this file, change it back!

2022-01-13 16:38 UTC, SamTo83 commented on src/components/PageHeader/PageHeader.jsx
> -            altContent={altContent}
added this back

2022-01-13 16:39 UTC, SamTo83 commented on src/components/Layout/Layout.scss
> +  overflow-y: hidden;
This is already there.

2022-01-13 17:11 UTC, DanForder requested changes

2022-01-13 17:11 UTC, DanForder commented on src/components/Paragraph/Paragraph.jsx
> +    </Fragment>
don't need a ternary for the whole thing here, the only thing that's different is that one extra class. So could do a ternary just inside that classname

2022-01-13 17:11 UTC, DanForder commented on src/components/PageHeader/PageHeader.scss
> +  }
remove

2022-01-13 17:25 UTC, noahSerafin commented on src/components/Paragraph/Paragraph.jsx
> +    </Fragment>
I've sorted this and committed, but I'm not sure if its in the PR

2022-01-14 09:17 UTC, DanForder requested changes
run format

2022-01-14 15:35 UTC, DanForder approved these changes

2022-01-17 10:21 UTC, merged